tool_categories:
  # Kategorie für "aktive Kunden" / "laufende Einsätze"
  active_customers_query:
    patterns:
      - wie viele kunden
      - aktive kunden
      - laufende einsätze
      - laufende carestays
      - wie viele betreue ich
      - aktuelle betreuungen
      - momentan betreuung
      - aktuell
      - jetzt
      - gerade
      - laufen
      - vertrag haben
      - how many customers
      - buchungen
    default_tool: get_active_care_stays_now  # Geändert zu get_active_care_stays_now

  # Kategorie für Kündigungen
  termination_query:
    patterns:
      - kündigungen
      - gekündigt
      - vertrag beendet
      - kunden verloren
      - abgesprungen
      - nicht verlängert
      - vertrag nicht verlängert
      - betreuung beendet
      - einsatz beendet
      - nicht mehr
      - ausstiege
    default_tool: get_contract_terminations

  # Kategorie für Lead-Abfragen
  lead_query:
    patterns:
      - wie viele leads
      - lead gekauft
      - leads genommen
      - lead-kauf
      - leads reklamiert
      - brutto leads
      - netto leads
      - verfügbare leads
      - lead
      - interessenten
      - potenzielle kunden
      - neue anfragen
    default_tool: get_recent_leads

  # Kategorie für Agentur-spezifische Abfragen
  agency_query:
    patterns:
      - agentur
      - vermittlung
      - anbieter
      - vermittelt
      - arbeite ich mit
      - von der agentur
      - mit der agentur
      - verträge mit
      - kunden bei
      - senioport
      - medipe
      - promedica
      - pflegeagentur
      - umsatz nach agentur
      - revenue by agency
      - einnahmen agentur
    default_tool: get_revenue_by_agency  # Geändert zu get_revenue_by_agency

  # Kategorie für Betreuungspausen
  care_pause_query:
    patterns:
      - pause
      - pausiert
      - pausieren
      - zwischen zwei einsätzen
      - betreuungspause
      - pflegepause
      - lücke
      - wartend
      - ohne betreuung
      - keine pflegekraft
      - in pause
      - welche kunden sind in pause
      - pause seit
    default_tool: get_customers_on_pause

  # Kategorie für kundenbezogene Abfragen
  customer_details_query:
    patterns:
      - kunde seit
      - wie lange
      - wie viele einsätze
      - wie oft gewechselt
      - wann gestartet
      - historie
      - verlauf
      - geschichte
      - erzähl mir
      - details zu
      - alles über
      - erzähl mir von kunde
      - infos zum kunden
      - kundenhistorie
    default_tool: get_customer_history

  # Kategorie für zeitraumbezogene Abfragen (erweitert)
  time_query:
    patterns:
      - carestays
      - einsätze
      - betreuungen
      - monat
      - monatlich
      - jahr
      - jährlich
      - januar
      - februar
      - märz
      - april
      - mai
      - juni
      - juli
      - august
      - september
      - oktober
      - november
      - dezember
      - zeitraum
      - von bis
      - zwischen
      - in
      - nächst
      - vergangen
      - letztes
    default_tool: get_care_stays_by_date_range

  # Kategorie für Monats-Performance Abfragen
  performance_query:
    patterns:
      - monthly performance
      - monatliche leistung
      - monatlicher umsatz
      - monatsleistung
      - monatliche zahlen
      - monatsauswertung
      - performance im monat
      - leistung im monat
      - monatsbilanz
      - ergebnis monat
      - leistung februar
      - leistung märz
      - leistung januar
    default_tool: get_monthly_performance

# Fallback-Tool, wenn keine Kategorie erkannt wird
fallback_tool: get_active_care_stays_now

# Direkte Muster-zu-Tool Zuordnungen für sehr spezifische Anfragen
force_tool_patterns:
  get_active_care_stays_now:
    - "wie viele kunden betreue ich gerade"
    - "aktuelle betreuungen"
    - "laufende carestays"
    - "aktive kunden"
    - "wie viele kunden habe ich momentan"
    - "aktuelle buchungen"
    - "jetzt gerade"
    - "aktuell"
  
  get_customers_on_pause:
    - "pause"
    - "pausiert"
    - "in pause"
    - "kunden ohne betreuung"
    - "kunden in pause"
    - "welche kunden pausieren"
    - "wer pausiert"
    - "wer hat keine betreuung"

  get_contract_terminations:
    - "kündigungen"
    - "gekündigt"
    - "vertrag beendet"
    - "beendete verträge"
    - "vertragsbeendigung"
    - "vertragsende"
    
  get_monthly_performance:
    - "monthly performance"
    - "monatliche leistung"
    - "performance im monat"
    - "leistung februar"
    - "leistungsbilanz"
    - "monatsbilanz"